name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target:
          - x86_64-pc-windows-msvc

    steps:
    - uses: actions/checkout@v2
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: ${{ matrix.target }}
        override: true
    - name: Build
      run: cargo build --release --target ${{ matrix.target }}
    - name: Upload Release Asset
      uses: actions/upload-artifact@v2
      with:
        name: digger-windows
        path: target/${{ matrix.target }}/release/digger.exe
