name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        target:
          - x86_64-pc-windows-msvc

    steps:
    - uses: actions/checkout@v4
    - name: Install Rust
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain stable
        rustup target add ${{ matrix.target }}
    - name: Build
      run: cargo build --release --target ${{ matrix.target }}
    - name: Upload Release Asset
      uses: actions/upload-artifact@v4
      with:
        name: digger-windows
        path: target/${{ matrix.target }}/release/digger.exe
